blank_issues_enabled: true
contact_links:
  - name: future Core Security Policy
    url: https://github.com/future/future/blob/master/SECURITY.md
    about: View security policy
  - name: future Core Developers
    url: https://futurecore.org
    about: future Core homepage
